version: '2.1'

services:
  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-agent
    image: doggie6/jenkins-swarm-agent:3.3
    privileged: true
    environment:
      - COMMAND_OPTIONS=-master ${JENKINS_ADDRESS} -username ${USER} -password ${PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - volume_jenkins-agent:/home/jenkins/
      - volume_jenkins-agent_maven:/opt/maven/
    restart: always